// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxnmlutalluvqwooznrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bm1sdXRhbGx1dnF3b296bnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjA1NTAsImV4cCI6MjA2NzY5NjU1MH0.29eIWadLXbmctbwSb1kLh7CGFZv9W0yNtKaDwPabJlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});